### ISSUE TITLE
Amber color instead of greenish.

### ISSUE THREAD

**Issue by OompaLoompaa** [corphish/NightLight#1]
Hi, congrats for the app. I really like what you have done but your implementation is a bit greenish.
As a OP3 owner, on OOS I struggled a lot with it's greenish night mode. I had seen Night mode on other devices and the Amber color is what suits best the night mode. AOSP has this very well implemented.
So I came to the conclusion that Kcal would have to benefit me with the absent Amber colored night mode on OOS.
The values I use are 256/190/135 (RGB).
Would you consider adding this configuration to your app, maybe as an extra option.
That would make it perfectly inline with Nougat night mode implementation.
Thank you for your time.

**Comment by corphish** [comment]
Ok I guess I will add support for support adjusting all the 3 colors.

**Comment by OompaLoompaa** [comment]
Well, that you can easily do with any kernel tweaking app that supports Kcal. What I thought you were trying to achieve was a way to enable night mode via Kcal on unsupported devices/Android versions like MM, using a simple tile/automatic scheduled. If you test those values against actual night mode shipped on AOSP N ROMs the conclusion is simple. Those mimic the original AOSP night mode flawlessly.
I don't really know if adding just support for the three RGB values would make users adjust it to this reference level by their own.
Well, it's just a little input from a crazy night mode user. 
The app is yours, and I really enjoy it apart from the greenish look it provides.
Hope you understand my concerns. 
And congrats once again.

**Comment by james-s-w-clark** [comment]
CF Lumen has various presets, like "Red", "Green", "Blue", "Amber", "Salmon", "Greyscale", "Invert", "Temperature" (slide bar), "Custom" (RGB 255 scales), "Colourblindness". Food for thought.

**Comment by corphish** [comment]
For now, green light filter support is added, which can be tuned along with blue light to get the amber color.
Check https://github.com/corphish/NightLight/commit/619b2c77f38f1c8471d21919ceada24f2ffcc306
