### ISSUE TITLE
Colour temperature

### ISSUE THREAD

**Issue by timea-techgirl** [corphish/NightLight#2]
Thanks for the fantastic app. Can you please add support for changing colour temperatures? like lineage os live display feature. I have aosp rom and I don't want to install lineage os but want live display feature. It will be perfect. Thank you.

**Comment by corphish** [comment]
I will see if it is possible with KCAL, if so then will definitely add it.

**Comment by timea-techgirl** [comment]
I'm glad. Thank you so much.

**Comment by corphish** [comment]
Has been finally implemented 😂.
See https://github.com/corphish/NightLight/commit/bbb04659fa3d3cfbb7f7303f3795dd99b0f064d9  (and other related commits)

**Comment by timea-techgirl** [comment]
Oh haha thank you. I will wait for the update on play store.
