### ISSUE TITLE
delay apply settings on boot - feature request

### ISSUE THREAD

**Issue by ghost** [corphish/NightLight#20]
hi,
could you please consider add time delay to apply setting after boot (eg customisable)
I have a crash with your app, when it try to apply values to kcal
I had the same with kernel adiutor and delay (20 sec)  resolved problems
thanks

**Comment by corphish** [comment]
Yes that can be done

**Comment by corphish** [comment]
See https://github.com/corphish/NightLight/commit/f9b0f07509d524f687400a399c279d5e7cf3fca7 https://github.com/corphish/NightLight/commit/5e4cc7ceb87af7bbecc67217b890216bfe775155 https://github.com/corphish/NightLight/commit/ff8ba2be2711445c47ccd49254ce5d04d4ab1173 https://github.com/corphish/NightLight/commit/05ec96f7f370944d27130f9fd528297303285725
