### ISSUE TITLE
Viewing most settings crashes the application

### ISSUE THREAD

**Issue by Iron-E** [corphish/NightLight#33]
Running version 3.0.0 Pro from Google Play, attempting to adjust nearly any setting causes the app to stop responding.

The previous 2.X version worked just fine for this, so it must be something that has changed from 2.X to 3.0.

The broken screens are:

- Bed Time (can't turn it on)
- Automation
- Default KCAL values
- Set on boot
- Lock screen
- Settings (there is a second menu called "settings" under settings)
- KCAL driver

The working screens are:

- Master controls
- Color controls
- KCAL brightness
- Profiles

**Comment by said50** [comment]
Same with me

**Comment by corphish** [comment]
It looks like obfuscation issue in pro version. I have pushed an update (version 3.0.1, code - 67) to Google Play (which should be live soon) that should fix this issue and all the settings should be accessible. Let me know if it works or not.

**Comment by Iron-E** [comment]
It works, thank you!
