### ISSUE TITLE
Fade from "normal" KCAL settings to chosen redness

### ISSUE THREAD

**Issue by james-s-w-clark** [corphish/NightLight#4]
Like in e.g. F.Lux.

**Comment by corphish** [comment]
This can be done by filtering out the green light, which will, along with filtered blue light, make red light more persistent and prominent, resulting in reddish tint.
Support for filtering green light was added in https://github.com/corphish/NightLight/commit/619b2c77f38f1c8471d21919ceada24f2ffcc306.
Let me know if green light filtering needs more flexibility.

**Comment by james-s-w-clark** [comment]
By fade I mean have the colours slowly change over time (seconds, minutes, or hours).

**Comment by corphish** [comment]
Oh ok..

**Comment by greasysock** [comment]
I can look into adding this feature because I am interested in having this as well.

**Comment by kocane** [comment]
@greasysock did you succeed? It'd be pretty cool to have a fading function, like CF.lumen used to do

**Comment by corphish** [comment]
Added in version 3.0.0 (which is in beta as of now).
