### ISSUE TITLE
Night Light isn't enable after reboot

### ISSUE THREAD

**Issue by dom133** [corphish/NightLight#9]
When I reboot device Nigh tLight don't enable again, BootCompleteReceiver is done but Night Light isnt enable. Only this line https://github.com/corphish/NightLight/blob/master/app/src/main/java/com/corphish/nightlight/Engine/Core.java#L23 is done. I use Magisk for root

**Comment by corphish** [comment]
Will be possibly fixed now that set on boot delay has been implemented.
